version: '2'
services:
  app:
    image: python:3.6-onbuild
    ports:
      - 5000:5000
    volumes:
      - ./:./
    command: ["python", "run.py"]

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
